name: RDP_TIPSUNIX

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Create Ansible Playbook
        run: |
          cat > playbook.yml << 'EOF'
          ---
          - name: Install Proxmox VE 8.4
            hosts: proxmox_host
            become: yes
            vars:
              tailscale_auth_key: "tskey-auth-kbUdFxeubs11CNTRL-NHrJK32vtphPF6rRH3gHqhQ1fkwv9GaqF"
              root_password: "RootSecurePass123!"

            tasks:
              - name: Update system
                apt:
                  update_cache: yes
                  upgrade: yes

              - name: Install required packages for Proxmox
                apt:
                  name:
                    - curl
                    - wget
                    - gnupg
                    - openssh-server
                  state: present

              - name: Add Proxmox repository key
                shell: |
                  wget -O- "http://download.proxmox.com/debian/proxmox-release-bookworm.gpg" | apt-key add -

              - name: Add Proxmox repository
                lineinfile:
                  path: /etc/apt/sources.list.d/pve-install-repo.list
                  line: "deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription"
                  create: yes

              - name: Update package list
                apt:
                  update_cache: yes

              - name: Install Proxmox VE
                apt:
                  name: proxmox-ve
                  state: present

              - name: Install postfix (required for Proxmox)
                apt:
                  name: postfix
                  state: present

              - name: Set root password
                user:
                  name: root
                  password: "{{ root_password | password_hash('sha512') }}"

              - name: Install Tailscale
                shell: |
                  curl -fsSL https://pkgs.tailscale.com/stable/debian/bookworm.gpg | apt-key add -
                  curl -fsSL https://pkgs.tailscale.com/stable/debian/bookworm.list | tee /etc/apt/sources.list.d/tailscale.list
                  apt update
                  apt install -y tailscale
                register: tailscale_install
                retries: 3
                delay: 10
                until: tailscale_install.rc == 0

              - name: Start Tailscale
                shell: |
                  tailscale up --authkey={{ tailscale_auth_key }} --hostname=proxmox-host
                become: yes
                register: tailscale_up
                retries: 3
                delay: 10
                until: tailscale_up.rc == 0

              - name: Enable Tailscale to start on boot
                systemd:
                  name: tailscaled
                  enabled: yes

              - name: Enable SSH
                systemd:
                  name: ssh
                  enabled: yes
                  state: started
          EOF

      - name: Create Inventory
        run: |
          cat > inventory.ini << 'EOF'
          [proxmox_host]
          your-proxmox-host ansible_host=your-proxmox-ip ansible_user=root

          [rdp_vms]
          # VMs will be added dynamically
          EOF

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory.ini playbook.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: false
          PROXMOX_API_USER: ${{ secrets.PROXMOX_API_USER }}
          PROXMOX_API_PASSWORD: ${{ secrets.PROXMOX_API_PASSWORD }}
          PROXMOX_NODE: ${{ secrets.PROXMOX_NODE }}
          PROXMOX_API_TOKEN_ID: ${{ secrets.PROXMOX_API_TOKEN_ID }}
          PROXMOX_API_TOKEN_SECRET: ${{ secrets.PROXMOX_API_TOKEN_SECRET }}

      - name: Display SSH Access Information
        run: |
          echo "=== SSH ACCESS INFORMATION ==="
          echo "Proxmox Host IP: ${{ secrets.PROXMOX_HOST_IP }}"
          echo "Username: root"
          echo "Password: ${{ secrets.PROXMOX_ROOT_PASSWORD }}"
          echo ""
          echo "Proxmox will be accessible via Tailscale network."
          echo "=================================="
