name: RDP_TIPSUNIX

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible
          ansible-galaxy collection install community.proxmox

      - name: Run Ansible Playbook
        run: |
          # === Buat file inventory dengan IP/host dari secret ===
          cat > inventory.ini << 'EOF'
          [proxmox_host]
          proxmox ansible_host=${{ secrets.PROXMOX_HOST_IP }} ansible_user=root ansible_ssh_pass=${{ secrets.PROXMOX_ROOT_PASSWORD }}
          EOF

          # === Jalankan playbook instalasi Proxmox ===
          ansible-playbook -i inventory.ini /dev/stdin << 'EOF'
          ---
          - name: Install Proxmox VE 8.4
            hosts: proxmox_host
            become: yes
            vars:
              tailscale_auth_key: "${{ secrets.TAILSCALE_AUTH_KEY }}"
              root_password: "${{ secrets.PROXMOX_ROOT_PASSWORD }}"

            tasks:
              - name: Update system
                apt:
                  update_cache: yes
                  upgrade: yes

              - name: Install required packages for Proxmox
                apt:
                  name:
                    - curl
                    - wget
                    - gnupg
                    - openssh-server
                  state: present

              - name: Add Proxmox repository key
                shell: |
                  wget -O- "http://download.proxmox.com/debian/proxmox-release-bookworm.gpg" | apt-key add -

              - name: Add Proxmox repository
                copy:
                  dest: /etc/apt/sources.list.d/pve-install-repo.list
                  content: |
                    deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription

              - name: Update package list
                apt:
                  update_cache: yes

              - name: Install Proxmox VE
                apt:
                  name: proxmox-ve
                  state: present

              - name: Install postfix (required for Proxmox)
                apt:
                  name: postfix
                  state: present

              - name: Set root password
                user:
                  name: root
                  password: "{{ root_password | password_hash('sha512') }}"

              - name: Install Tailscale
                shell: |
                  curl -fsSL https://pkgs.tailscale.com/stable/debian/bookworm.gpg | sudo apt-key add -
                  curl -fsSL https://pkgs.tailscale.com/stable/debian/bookworm.list | sudo tee /etc/apt/sources.list.d/tailscale.list
                  apt update
                  apt install -y tailscale
                register: tailscale_install
                retries: 3
                delay: 10
                until: tailscale_install.rc == 0

              - name: Start Tailscale
                shell: |
                  tailscale up --authkey={{ tailscale_auth_key }} --hostname=proxmox-host
                become: yes
                register: tailscale_up
                retries: 3
                delay: 10
                until: tailscale_up.rc == 0

              - name: Enable Tailscale to start on boot
                systemd:
                  name: tailscaled
                  enabled: yes

              - name: Enable SSH
                systemd:
                  name: ssh
                  enabled: yes
                  state: started
          EOF
        env:
          ANSIBLE_HOST_KEY_CHECKING: false

      - name: Display SSH Access Information
        run: |
          echo "=== SSH ACCESS INFORMATION ==="
          echo "Proxmox Host IP: ${{ secrets.PROXMOX_HOST_IP }}"
          echo "Username: root"
          echo "Password: ${{ secrets.PROXMOX_ROOT_PASSWORD }}"
          echo ""
          echo "Proxmox akan bisa diakses lewat jaringan Tailscale."
          echo "=================================="
